# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('alias', models.CharField(blank=True, db_index=True, help_text='做伪静态url用', max_length=200, null=True, verbose_name='英文标题')),
                ('tags', models.CharField(blank=True, help_text='用英文逗号分割', max_length=100, null=True, verbose_name='标签')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('summary', models.TextField(max_length=1500, verbose_name='摘要')),
                ('content', models.TextField(max_length=20000, verbose_name='文章正文rst/md格式')),
                ('content_html', models.TextField(max_length=500, verbose_name='文章正文html')),
                ('view_times', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_md', models.BooleanField(default=False, verbose_name='是否为mardown格式')),
                ('is_old', models.BooleanField(default=False, verbose_name='是否为旧数据')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ['-is_top', '-pub_time', '-create_time'],
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('alias', models.CharField(max_length=40, verbose_name='英文名分类')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, verbose_name='状态')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否在导航位置显示')),
                ('rank', models.IntegerField(default=0, verbose_name='展示排序')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soblog.Catagory', verbose_name='上级分类')),
            ],
            options={
                'ordering': ['rank'],
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=240, verbose_name='评论内容')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soblog.Blog', verbose_name='文章')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_catagory', to='soblog.Catagory', verbose_name='分类'),
        ),
    ]
