# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='若留空, 则使用默认图片', null=True, upload_to='uploads/avatars/%Y/%m/%d', verbose_name='本地头像图片'),
        ),
    ]
