# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.ForeignKey(default='Unamed', on_delete=django.db.models.deletion.CASCADE, to='soblog.Userinfo', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='adma', max_length=16, verbose_name='站长'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soblog.Userinfo', verbose_name='用户名'),
        ),
    ]
