# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0003_auto_20170201_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='adma', max_length=16, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='博客正文'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='soblog.Blog', verbose_name='博客'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=240, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=16, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, verbose_name='标签名称'),
        ),
    ]
