# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0003_auto_20170216_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.URLField(blank=True, null=True, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_catagory', to='soblog.Catagory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='文章正文rst/md格式'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_html',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='文章正文html'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '正常'), (1, '草稿'), (2, '删除')], default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数'),
        ),
    ]
