# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0004_auto_20170201_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
