# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soblog', '0005_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='blog_abstract'),
        ),
        migrations.AddField(
            model_name='blog',
            name='bloger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soblog.Userinfo'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='pub_time'),
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='view_count'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='comment_time'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_login_date)'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last_login_ip'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=7, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, default='adma', max_length=16, null=True, verbose_name='blog_author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soblog.Catagory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='blog_content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='soblog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='blog_title'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='catagory'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='soblog.Blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=240, verbose_name='comment_content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='commenter'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=16, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=16, verbose_name='username'),
        ),
    ]
